/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AIfStatement extends PStatement
{
    private PExpression _condition_;
    private final LinkedList<PStatement> _true_ = new LinkedList<PStatement>();
    private final LinkedList<PStatement> _false_ = new LinkedList<PStatement>();

    public AIfStatement()
    {
        // Constructor
    }

    public AIfStatement(
        @SuppressWarnings("hiding") PExpression _condition_,
        @SuppressWarnings("hiding") List<?> _true_,
        @SuppressWarnings("hiding") List<?> _false_)
    {
        // Constructor
        setCondition(_condition_);

        setTrue(_true_);

        setFalse(_false_);

    }

    @Override
    public Object clone()
    {
        return new AIfStatement(
            cloneNode(this._condition_),
            cloneList(this._true_),
            cloneList(this._false_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStatement(this);
    }

    public PExpression getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PExpression node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public LinkedList<PStatement> getTrue()
    {
        return this._true_;
    }

    public void setTrue(List<?> list)
    {
        for(PStatement e : this._true_)
        {
            e.parent(null);
        }
        this._true_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._true_.add(e);
        }
    }

    public LinkedList<PStatement> getFalse()
    {
        return this._false_;
    }

    public void setFalse(List<?> list)
    {
        for(PStatement e : this._false_)
        {
            e.parent(null);
        }
        this._false_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._false_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condition_)
            + toString(this._true_)
            + toString(this._false_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._true_.remove(child))
        {
            return;
        }

        if(this._false_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condition_ == oldChild)
        {
            setCondition((PExpression) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._true_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PStatement> i = this._false_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
