/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AStart extends PStart
{
    private final LinkedList<PClassDefinition> _classDefinition_ = new LinkedList<PClassDefinition>();

    public AStart()
    {
        // Constructor
    }

    public AStart(
        @SuppressWarnings("hiding") List<?> _classDefinition_)
    {
        // Constructor
        setClassDefinition(_classDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AStart(
            cloneList(this._classDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStart(this);
    }

    public LinkedList<PClassDefinition> getClassDefinition()
    {
        return this._classDefinition_;
    }

    public void setClassDefinition(List<?> list)
    {
        for(PClassDefinition e : this._classDefinition_)
        {
            e.parent(null);
        }
        this._classDefinition_.clear();

        for(Object obj_e : list)
        {
            PClassDefinition e = (PClassDefinition) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._classDefinition_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classDefinition_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PClassDefinition> i = this._classDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClassDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
