/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterThanExpression extends PExpression
{
    private PExpression _lhs_;
    private PExpression _rhs_;

    public AGreaterThanExpression()
    {
        // Constructor
    }

    public AGreaterThanExpression(
        @SuppressWarnings("hiding") PExpression _lhs_,
        @SuppressWarnings("hiding") PExpression _rhs_)
    {
        // Constructor
        setLhs(_lhs_);

        setRhs(_rhs_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterThanExpression(
            cloneNode(this._lhs_),
            cloneNode(this._rhs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterThanExpression(this);
    }

    public PExpression getLhs()
    {
        return this._lhs_;
    }

    public void setLhs(PExpression node)
    {
        if(this._lhs_ != null)
        {
            this._lhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lhs_ = node;
    }

    public PExpression getRhs()
    {
        return this._rhs_;
    }

    public void setRhs(PExpression node)
    {
        if(this._rhs_ != null)
        {
            this._rhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rhs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lhs_)
            + toString(this._rhs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lhs_ == child)
        {
            this._lhs_ = null;
            return;
        }

        if(this._rhs_ == child)
        {
            this._rhs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lhs_ == oldChild)
        {
            setLhs((PExpression) newChild);
            return;
        }

        if(this._rhs_ == oldChild)
        {
            setRhs((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
