/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AStringType extends PType
{
    private TStringClass _stringClass_;

    public AStringType()
    {
        // Constructor
    }

    public AStringType(
        @SuppressWarnings("hiding") TStringClass _stringClass_)
    {
        // Constructor
        setStringClass(_stringClass_);

    }

    @Override
    public Object clone()
    {
        return new AStringType(
            cloneNode(this._stringClass_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringType(this);
    }

    public TStringClass getStringClass()
    {
        return this._stringClass_;
    }

    public void setStringClass(TStringClass node)
    {
        if(this._stringClass_ != null)
        {
            this._stringClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringClass_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringClass_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringClass_ == child)
        {
            this._stringClass_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringClass_ == oldChild)
        {
            setStringClass((TStringClass) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
