/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.analysis;

import com.bju.cps450.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTStringLiteral(TStringLiteral node);
    void caseTUnterminatedStr(TUnterminatedStr node);
    void caseTIllegalStr(TIllegalStr node);
    void caseTIntegerLiteral(TIntegerLiteral node);
    void caseTClass(TClass node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTMain(TMain node);
    void caseTStringClass(TStringClass node);
    void caseTExtends(TExtends node);
    void caseTInt(TInt node);
    void caseTBoolean(TBoolean node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTThis(TThis node);
    void caseTNew(TNew node);
    void caseTLeftCurly(TLeftCurly node);
    void caseTRightCurly(TRightCurly node);
    void caseTLeftParen(TLeftParen node);
    void caseTRightParen(TRightParen node);
    void caseTLeftBracket(TLeftBracket node);
    void caseTRightBracket(TRightBracket node);
    void caseTSemicolon(TSemicolon node);
    void caseTEquals(TEquals node);
    void caseTLessThan(TLessThan node);
    void caseTGreaterThan(TGreaterThan node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMultiplication(TMultiplication node);
    void caseTDivides(TDivides node);
    void caseTDot(TDot node);
    void caseTComma(TComma node);
    void caseTNot(TNot node);
    void caseTOr(TOr node);
    void caseTAnd(TAnd node);
    void caseTComment(TComment node);
    void caseTWhitespace(TWhitespace node);
    void caseTEndOfLine(TEndOfLine node);
    void caseTIdentifier(TIdentifier node);
    void caseTUnknownCharacter(TUnknownCharacter node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
