/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AAndExpressionLvl5 extends PExpressionLvl5
{
    private PExpressionLvl5 _expressionLvl5_;
    private TAnd _and_;
    private PExpressionLvl4 _expressionLvl4_;

    public AAndExpressionLvl5()
    {
        // Constructor
    }

    public AAndExpressionLvl5(
        @SuppressWarnings("hiding") PExpressionLvl5 _expressionLvl5_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExpressionLvl4 _expressionLvl4_)
    {
        // Constructor
        setExpressionLvl5(_expressionLvl5_);

        setAnd(_and_);

        setExpressionLvl4(_expressionLvl4_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpressionLvl5(
            cloneNode(this._expressionLvl5_),
            cloneNode(this._and_),
            cloneNode(this._expressionLvl4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpressionLvl5(this);
    }

    public PExpressionLvl5 getExpressionLvl5()
    {
        return this._expressionLvl5_;
    }

    public void setExpressionLvl5(PExpressionLvl5 node)
    {
        if(this._expressionLvl5_ != null)
        {
            this._expressionLvl5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl5_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExpressionLvl4 getExpressionLvl4()
    {
        return this._expressionLvl4_;
    }

    public void setExpressionLvl4(PExpressionLvl4 node)
    {
        if(this._expressionLvl4_ != null)
        {
            this._expressionLvl4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl5_)
            + toString(this._and_)
            + toString(this._expressionLvl4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl5_ == child)
        {
            this._expressionLvl5_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._expressionLvl4_ == child)
        {
            this._expressionLvl4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl5_ == oldChild)
        {
            setExpressionLvl5((PExpressionLvl5) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._expressionLvl4_ == oldChild)
        {
            setExpressionLvl4((PExpressionLvl4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
