/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ALtExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl3 _first_;
    private TLessThan _lessThan_;
    private PExpressionLvl3 _expressionLvl3_;

    public ALtExpressionLvl4()
    {
        // Constructor
    }

    public ALtExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl3 _first_,
        @SuppressWarnings("hiding") TLessThan _lessThan_,
        @SuppressWarnings("hiding") PExpressionLvl3 _expressionLvl3_)
    {
        // Constructor
        setFirst(_first_);

        setLessThan(_lessThan_);

        setExpressionLvl3(_expressionLvl3_);

    }

    @Override
    public Object clone()
    {
        return new ALtExpressionLvl4(
            cloneNode(this._first_),
            cloneNode(this._lessThan_),
            cloneNode(this._expressionLvl3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtExpressionLvl4(this);
    }

    public PExpressionLvl3 getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExpressionLvl3 node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TLessThan getLessThan()
    {
        return this._lessThan_;
    }

    public void setLessThan(TLessThan node)
    {
        if(this._lessThan_ != null)
        {
            this._lessThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThan_ = node;
    }

    public PExpressionLvl3 getExpressionLvl3()
    {
        return this._expressionLvl3_;
    }

    public void setExpressionLvl3(PExpressionLvl3 node)
    {
        if(this._expressionLvl3_ != null)
        {
            this._expressionLvl3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._lessThan_)
            + toString(this._expressionLvl3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._lessThan_ == child)
        {
            this._lessThan_ = null;
            return;
        }

        if(this._expressionLvl3_ == child)
        {
            this._expressionLvl3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PExpressionLvl3) newChild);
            return;
        }

        if(this._lessThan_ == oldChild)
        {
            setLessThan((TLessThan) newChild);
            return;
        }

        if(this._expressionLvl3_ == oldChild)
        {
            setExpressionLvl3((PExpressionLvl3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
