/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AMethodCallExpr extends PMethodCallExpr
{
    private PExpressionLvl0 _expressionLvl0_;
    private TDot _dot_;

    public AMethodCallExpr()
    {
        // Constructor
    }

    public AMethodCallExpr(
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_,
        @SuppressWarnings("hiding") TDot _dot_)
    {
        // Constructor
        setExpressionLvl0(_expressionLvl0_);

        setDot(_dot_);

    }

    @Override
    public Object clone()
    {
        return new AMethodCallExpr(
            cloneNode(this._expressionLvl0_),
            cloneNode(this._dot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodCallExpr(this);
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl0_)
            + toString(this._dot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
