/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class ANegExpressionLvl1 extends PExpressionLvl1
{
    private TMinus _minus_;
    private PExpressionLvl1 _expressionLvl1_;

    public ANegExpressionLvl1()
    {
        // Constructor
    }

    public ANegExpressionLvl1(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExpressionLvl1 _expressionLvl1_)
    {
        // Constructor
        setMinus(_minus_);

        setExpressionLvl1(_expressionLvl1_);

    }

    @Override
    public Object clone()
    {
        return new ANegExpressionLvl1(
            cloneNode(this._minus_),
            cloneNode(this._expressionLvl1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegExpressionLvl1(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExpressionLvl1 getExpressionLvl1()
    {
        return this._expressionLvl1_;
    }

    public void setExpressionLvl1(PExpressionLvl1 node)
    {
        if(this._expressionLvl1_ != null)
        {
            this._expressionLvl1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._expressionLvl1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._expressionLvl1_ == child)
        {
            this._expressionLvl1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._expressionLvl1_ == oldChild)
        {
            setExpressionLvl1((PExpressionLvl1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
