/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AOrExpressionLvl6 extends PExpressionLvl6
{
    private PExpressionLvl6 _expressionLvl6_;
    private TOr _or_;
    private PExpressionLvl5 _expressionLvl5_;

    public AOrExpressionLvl6()
    {
        // Constructor
    }

    public AOrExpressionLvl6(
        @SuppressWarnings("hiding") PExpressionLvl6 _expressionLvl6_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PExpressionLvl5 _expressionLvl5_)
    {
        // Constructor
        setExpressionLvl6(_expressionLvl6_);

        setOr(_or_);

        setExpressionLvl5(_expressionLvl5_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpressionLvl6(
            cloneNode(this._expressionLvl6_),
            cloneNode(this._or_),
            cloneNode(this._expressionLvl5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpressionLvl6(this);
    }

    public PExpressionLvl6 getExpressionLvl6()
    {
        return this._expressionLvl6_;
    }

    public void setExpressionLvl6(PExpressionLvl6 node)
    {
        if(this._expressionLvl6_ != null)
        {
            this._expressionLvl6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl6_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PExpressionLvl5 getExpressionLvl5()
    {
        return this._expressionLvl5_;
    }

    public void setExpressionLvl5(PExpressionLvl5 node)
    {
        if(this._expressionLvl5_ != null)
        {
            this._expressionLvl5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl6_)
            + toString(this._or_)
            + toString(this._expressionLvl5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl6_ == child)
        {
            this._expressionLvl6_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._expressionLvl5_ == child)
        {
            this._expressionLvl5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl6_ == oldChild)
        {
            setExpressionLvl6((PExpressionLvl6) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._expressionLvl5_ == oldChild)
        {
            setExpressionLvl5((PExpressionLvl5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
