/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class APassExpressionLvl1 extends PExpressionLvl1
{
    private PExpressionLvl0 _expressionLvl0_;

    public APassExpressionLvl1()
    {
        // Constructor
    }

    public APassExpressionLvl1(
        @SuppressWarnings("hiding") PExpressionLvl0 _expressionLvl0_)
    {
        // Constructor
        setExpressionLvl0(_expressionLvl0_);

    }

    @Override
    public Object clone()
    {
        return new APassExpressionLvl1(
            cloneNode(this._expressionLvl0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPassExpressionLvl1(this);
    }

    public PExpressionLvl0 getExpressionLvl0()
    {
        return this._expressionLvl0_;
    }

    public void setExpressionLvl0(PExpressionLvl0 node)
    {
        if(this._expressionLvl0_ != null)
        {
            this._expressionLvl0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionLvl0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionLvl0_ == child)
        {
            this._expressionLvl0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionLvl0_ == oldChild)
        {
            setExpressionLvl0((PExpressionLvl0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
