/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AQtExpressionLvl4 extends PExpressionLvl4
{
    private PExpressionLvl3 _first_;
    private TGreaterThan _greaterThan_;
    private PExpressionLvl3 _expressionLvl3_;

    public AQtExpressionLvl4()
    {
        // Constructor
    }

    public AQtExpressionLvl4(
        @SuppressWarnings("hiding") PExpressionLvl3 _first_,
        @SuppressWarnings("hiding") TGreaterThan _greaterThan_,
        @SuppressWarnings("hiding") PExpressionLvl3 _expressionLvl3_)
    {
        // Constructor
        setFirst(_first_);

        setGreaterThan(_greaterThan_);

        setExpressionLvl3(_expressionLvl3_);

    }

    @Override
    public Object clone()
    {
        return new AQtExpressionLvl4(
            cloneNode(this._first_),
            cloneNode(this._greaterThan_),
            cloneNode(this._expressionLvl3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQtExpressionLvl4(this);
    }

    public PExpressionLvl3 getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExpressionLvl3 node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TGreaterThan getGreaterThan()
    {
        return this._greaterThan_;
    }

    public void setGreaterThan(TGreaterThan node)
    {
        if(this._greaterThan_ != null)
        {
            this._greaterThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThan_ = node;
    }

    public PExpressionLvl3 getExpressionLvl3()
    {
        return this._expressionLvl3_;
    }

    public void setExpressionLvl3(PExpressionLvl3 node)
    {
        if(this._expressionLvl3_ != null)
        {
            this._expressionLvl3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionLvl3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._greaterThan_)
            + toString(this._expressionLvl3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._greaterThan_ == child)
        {
            this._greaterThan_ = null;
            return;
        }

        if(this._expressionLvl3_ == child)
        {
            this._expressionLvl3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PExpressionLvl3) newChild);
            return;
        }

        if(this._greaterThan_ == oldChild)
        {
            setGreaterThan((TGreaterThan) newChild);
            return;
        }

        if(this._expressionLvl3_ == oldChild)
        {
            setExpressionLvl3((PExpressionLvl3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
