/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AStatementBlock extends PStatementBlock
{
    private TLeftCurly _leftCurly_;
    private final LinkedList<PStatement> _statement_ = new LinkedList<PStatement>();
    private TRightCurly _rightCurly_;

    public AStatementBlock()
    {
        // Constructor
    }

    public AStatementBlock(
        @SuppressWarnings("hiding") TLeftCurly _leftCurly_,
        @SuppressWarnings("hiding") List<?> _statement_,
        @SuppressWarnings("hiding") TRightCurly _rightCurly_)
    {
        // Constructor
        setLeftCurly(_leftCurly_);

        setStatement(_statement_);

        setRightCurly(_rightCurly_);

    }

    @Override
    public Object clone()
    {
        return new AStatementBlock(
            cloneNode(this._leftCurly_),
            cloneList(this._statement_),
            cloneNode(this._rightCurly_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementBlock(this);
    }

    public TLeftCurly getLeftCurly()
    {
        return this._leftCurly_;
    }

    public void setLeftCurly(TLeftCurly node)
    {
        if(this._leftCurly_ != null)
        {
            this._leftCurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftCurly_ = node;
    }

    public LinkedList<PStatement> getStatement()
    {
        return this._statement_;
    }

    public void setStatement(List<?> list)
    {
        for(PStatement e : this._statement_)
        {
            e.parent(null);
        }
        this._statement_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._statement_.add(e);
        }
    }

    public TRightCurly getRightCurly()
    {
        return this._rightCurly_;
    }

    public void setRightCurly(TRightCurly node)
    {
        if(this._rightCurly_ != null)
        {
            this._rightCurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightCurly_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftCurly_)
            + toString(this._statement_)
            + toString(this._rightCurly_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftCurly_ == child)
        {
            this._leftCurly_ = null;
            return;
        }

        if(this._statement_.remove(child))
        {
            return;
        }

        if(this._rightCurly_ == child)
        {
            this._rightCurly_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftCurly_ == oldChild)
        {
            setLeftCurly((TLeftCurly) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rightCurly_ == oldChild)
        {
            setRightCurly((TRightCurly) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
