/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AValuesList extends PValuesList
{
    private PExpression _expression_;
    private final LinkedList<PValuesListTail> _valuesListTail_ = new LinkedList<PValuesListTail>();

    public AValuesList()
    {
        // Constructor
    }

    public AValuesList(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _valuesListTail_)
    {
        // Constructor
        setExpression(_expression_);

        setValuesListTail(_valuesListTail_);

    }

    @Override
    public Object clone()
    {
        return new AValuesList(
            cloneNode(this._expression_),
            cloneList(this._valuesListTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValuesList(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PValuesListTail> getValuesListTail()
    {
        return this._valuesListTail_;
    }

    public void setValuesListTail(List<?> list)
    {
        for(PValuesListTail e : this._valuesListTail_)
        {
            e.parent(null);
        }
        this._valuesListTail_.clear();

        for(Object obj_e : list)
        {
            PValuesListTail e = (PValuesListTail) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._valuesListTail_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._valuesListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._valuesListTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PValuesListTail> i = this._valuesListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PValuesListTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
